server {
    listen 80;
    
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Configuración para que funcione React Router (Single Page Application)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Caché para los recursos estáticos para mejorar el rendimiento
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|mp4)$ {
        expires 6M;
        access_log off;
    }
}